### ISSUE TITLE
https://rpc.testnet.near.org/ being called by Pairing API

### ISSUE THREAD

**Issue by GrahamMcBain** [WalletConnect/web-examples#107]
Is that right? Why would we be using a near RPC testnet node?

**Comment by wayne-yu-anchorage** [comment]
The more important question is: what **is** the right Relay API URLs (for Production vs Testing, respectively)?
Note that this is for developers who do **not** intend to use any for the libraries (React, etc.) - instead, we would like to connect to the WebSocket service directly.

**Comment by finessevanes** [comment]
The relay url is `wss://relay.walletconnect.com`
https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0#migration-changes

The reason `https://rpc.testnet.near.org/` is being used is because this is the Near testnet RPC. The wallet example encompasses many different blockchain networks, such as Elrond's `https://devnet-api.elrond.com/`, and Polkadot's `wss://westend-rpc.polkadot.io`, etc."
