### ISSUE TITLE
Why Does Wallet .toLowerCase() the Address?

### ISSUE THREAD

**Issue by Luzzotica** [WalletConnect/web-examples#124]
https://github.com/WalletConnect/web-examples/blob/4bb9940a09c870dc95b1413850fafc1cf9042e6e/wallets/react-web3wallet/src/utils/HelperUtil.ts#L65

I'm getting an address from the wallet that has upper case characters, but the eth wallet expects lower case.

Is there a reason for this?
Why doesn't the wallet send me the address with lowercase characters?

I'll admit, I'm not 100% familiar with eth addresses, I feel like they aren't case sensitive, but I might be wrong.
If they are case sensitive, then we DEFINITELY shouldn't be lowercasing them in the example.

**Comment by bkrem** [comment]
Hi @Luzzotica,

Ethereum addresses are case insensitive, casing is only relevant for checksums
https://ethereum.stackexchange.com/questions/2045/is-ethereum-wallet-address-case-sensitive

This implementation (and other Ethereum libraries) generally lowercase any addresses before comparison as a normalisation measure, because as you already noted sometimes external address inputs will be mixed case, sometimes already fully lowercased. This avoids false negatives, where a mixed case address is compared to an (effectively matching) lowercase address.
