### ISSUE TITLE
@json-rpc-tools/utils is deprecated 

### ISSUE THREAD

**Issue by Neti-Sade** [WalletConnect/web-examples#132]
As you can see [here](https://www.npmjs.com/package/@json-rpc-tools/utils), `@json-rpc-tools/utils` package is deprecated.
Is there an alternative way to construct my response in the wallet, for example, in 
`web-examples/wallets/react-wallet-v2/src/utils/EIP155RequestHandlerUtil.ts`
all the responses are built with the formatJsonRpcResult method from this package.

**Comment by bkrem** [comment]
Hi @Neti-Sade,

I believe the package was deprecated in order to migrate the functionality into a different package: [`@walletconnect/jsonrpc-utils`](https://www.npmjs.com/package/@walletconnect/jsonrpc-utils)

You should be able to use the same functions as before when importing from that package instead.
