### ISSUE TITLE
react-app.walletconnect.com signature failing for lowercased addresses (Ethereum RPC Methods)

### ISSUE THREAD

**Issue by chrislang1** [WalletConnect/web-examples#18]
If a lowercased address is submitted as part of the session proposal, `personal_sign`, `eth_sign` and `eth_signTypedData` results will be declared invalid when received by dApp. Non-lowercased addresses pass.

**Comment by bkrem** [comment]
Thanks for making us aware of this @chrislang1!

This was due to `ethers.utils.verifyMessage/verifyTypedData` always returning a mixed-case recovered address (even if a lowercased address was the input), which then failed the identity check when comparing `recoveredAddress === address`

Should be fixed now across the dapp examples for the EIP155 methods you mentioned above. 

Please let me know here if validation is still failing for lowercase addresses so we can reopen if necessary.
