### ISSUE TITLE
Add methods to example

### ISSUE THREAD

**Issue by finessevanes** [WalletConnect/web-examples#219]
Currently the example: https://react-app.walletconnect.com/ only had the following methods to test:
- personal sign
- send transaction

Add:
- Sign typed data
- Sign transaction
- Send raw transaction

**Comment by bkrem** [comment]
These methods are all still available, but the logic in the sample dapp now properly excludes them from the session if the wallet didn't approve them, since all except `personal_sign` and `eth_sendTransaction` are proposed as optional.

See e.g. Rainbow in the screenshot below which does approve the optionals.

I've added a follow-up issue https://github.com/WalletConnect/web-examples/issues/220 to make this clearer in the UI, closing in favour of that.

<img width="711" alt="Screenshot 2023-07-04 at 10 37 19" src="https://github.com/WalletConnect/web-examples/assets/8663099/73fe98ea-324f-4282-9448-f22f2d12064d">

---
