### ISSUE TITLE
Type error: Cannot read properties of undefined ('reading message')

### ISSUE THREAD

**Issue by robliou** [WalletConnect/web-examples#32]
Hi!

After following the instructions to install WalletConnect (i.e. cloning the WalletConnect repository, running yarn, running yarn start), I get the error as follows:

**Type error: Cannot read properties of undefined ('reading message')**

This error pops up whether I am trying to run REACT-DAPP-V2 or REACT-DAPP-V2-WITH-WEB-JS.

It appears to be the same error experienced in issue #13, which was closed for some reason. Note that the solution that was proposed in issue #13 does not seem to be appropriate to solving this problem, since I am not trying to run the program from a branch directory or anything like that..

Has anyone else experienced this issue, or can please help me to solve it? Thanks,

**Comment by bkrem** [comment]
Hi @robliou,

This is most likely due to a missing projectId, since the repo only provides a placeholder value for this by default. You need to add to your `.env.local` file after you set it up via `cp .env.local.example .env.local` as explained here: https://github.com/WalletConnect/web-examples/tree/main/dapps/react-dapp-v2#running-locally

The error messaging here could definitely be clearer and is something we intend to improve as v2 beta progresses towards a stable release.

To get you up and running, you should be able to copy-paste the config below into your own `.env.local` file and everything should work:

```
REACT_APP_PROJECT_ID=e899c82be21d4acca2c8aec45e893598
REACT_APP_RELAY_URL=wss://relay.walletconnect.com
```

**This projectId is intended specifically for these demos, so please generate your own projectID on https://cloud.walletconnect.com if you want to start working with the v2 beta SDK in your own project :)**

Closing as resolved, but let us know if you're still experiencing this issue with the projectId in place and we can reopen 👍

**Comment by Dream552b** [comment]
configured REACT_APP_PROJECT_ID and REACT_APP_RELAY_URL ，there will still be problems 。Cannot read properties of undefined ('reading message')

ask for a solution

**Comment by bkrem** [comment]
Hi @Dream552b,

please see the instructions I originally linked above: https://github.com/WalletConnect/web-examples/tree/main/dapps/react-dapp-v2#running-locally

The env vars have been adjusted to work with Next.js (i.e. `NEXT_PUBLIC_...`) since the original response, I've updated the snippet in my original response to reflect that.
